# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l387KxdZghCG-Eysbauw8aF2KNPNK3El
"""

from google.colab import files
uploaded = files.upload()

# Burnout Early Detection — ML Pipeline
# Dataset: Student Stress Factors (Kaggle, n=1100)

!pip install scikit-learn pandas numpy matplotlib seaborn --quiet

import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns
import zipfile, os, warnings

warnings.filterwarnings('ignore')
matplotlib.rcParams['figure.dpi'] = 150

from sklearn.linear_model    import LogisticRegression
from sklearn.ensemble        import RandomForestClassifier
from sklearn.svm             import SVC
from sklearn.model_selection import train_test_split, cross_val_score, StratifiedKFold
from sklearn.preprocessing   import StandardScaler, label_binarize
from sklearn.metrics         import (accuracy_score, precision_score, recall_score,
                                     f1_score, confusion_matrix,
                                     classification_report, roc_curve, auc)

# ------------------------------------------------------------------
# STEP 1 — LOAD DATASET
# ------------------------------------------------------------------

df_raw = pd.read_csv('StressLevelDataset.csv')
print("Dataset loaded:", df_raw.shape)
print("Columns:", df_raw.columns.tolist())
print("\nFirst 3 rows:")
print(df_raw.head(3))

# ------------------------------------------------------------------
# STEP 2 — MAP TO 10 FEATURES
#
# Public columns → our features:
#   sleep_quality        → sleep_hours (high quality = more sleep)
#   headache             → sleep_deprivation (proxy)
#   study_load           → study_hours
#   academic_performance → overwhelmed (inverted: low performance = more overwhelmed)
#   depression           → stress_level + emotional_exhaust
#   self_esteem          → unmotivated (inverted)
#   extracurricular_activities → exercise_week
#   future_career_concerns     → screen_hours (proxy)
#   mental_health_history      → mental_fatigue
#   stress_level (original)    → label
# ------------------------------------------------------------------

def scale_col(series, new_min, new_max):
    old_min, old_max = series.min(), series.max()
    if old_max == old_min:
        return pd.Series([new_min] * len(series), index=series.index)
    scaled = (series - old_min) / (old_max - old_min) * (new_max - new_min) + new_min
    return scaled.round().astype(int)

df = pd.DataFrame()

df['sleep_hours']       = scale_col(df_raw['sleep_quality'], 1, 3)
df['sleep_deprivation'] = scale_col(df_raw['sleep_quality'].max() - df_raw['sleep_quality'], 1, 5)
df['study_hours']       = scale_col(df_raw['study_load'], 1, 4)
df['overwhelmed']       = scale_col(df_raw['academic_performance'].max() - df_raw['academic_performance'], 1, 5)
df['stress_level']      = scale_col(df_raw['depression'], 1, 5)
df['emotional_exhaust'] = scale_col(df_raw['depression'], 1, 5)
df['unmotivated']       = scale_col(df_raw['self_esteem'].max() - df_raw['self_esteem'], 1, 5)
df['exercise_week']     = scale_col(df_raw['extracurricular_activities'], 0, 3)
df['screen_hours']      = scale_col(df_raw['future_career_concerns'], 2, 4)
df['mental_fatigue']    = df_raw['mental_health_history'].apply(lambda x: 3 if x == 1 else 1)
df['label']             = df_raw['stress_level'].astype(int)

df = df.dropna().reset_index(drop=True)

print(f"\nMapped dataset: {df.shape}")
print("Class distribution:")
print(df['label'].value_counts().rename({0:'Low Risk',1:'Moderate Risk',2:'High Risk'}).sort_index())

# ------------------------------------------------------------------
# STEP 3 — SPLIT AND SCALE
# ------------------------------------------------------------------

FEAT = ['sleep_hours','sleep_deprivation','study_hours','overwhelmed',
        'stress_level','emotional_exhaust','unmotivated',
        'exercise_week','screen_hours','mental_fatigue']

X = df[FEAT]
y = df['label']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)
scaler     = StandardScaler()
X_train_sc = scaler.fit_transform(X_train)
X_test_sc  = scaler.transform(X_test)

print(f"\nTrain: {len(X_train)} | Test: {len(X_test)}")

# ------------------------------------------------------------------
# STEP 4 — TRAIN AND EVALUATE
# ------------------------------------------------------------------

models = {
    'Logistic Regression': LogisticRegression(max_iter=1000, random_state=42),
    'Random Forest':       RandomForestClassifier(n_estimators=100, random_state=42),
    'SVM (RBF)':           SVC(kernel='rbf', probability=True, random_state=42),
}

cv      = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
results = {}
CLASSES = ['Low Risk', 'Moderate Risk', 'High Risk']
COLORS  = ['#4472C4', '#70AD47', '#FF6B35']

for name, model in models.items():
    model.fit(X_train_sc, y_train)
    pred  = model.predict(X_test_sc)
    cv_sc = cross_val_score(model, scaler.transform(X), y, cv=cv, scoring='accuracy')
    results[name] = {
        'model':   model,   'pred':    pred,
        'acc':     accuracy_score(y_test, pred),
        'prec':    precision_score(y_test, pred, average='weighted', zero_division=0),
        'rec':     recall_score(y_test, pred, average='weighted', zero_division=0),
        'f1':      f1_score(y_test, pred, average='weighted', zero_division=0),
        'cv_mean': cv_sc.mean(), 'cv_std': cv_sc.std(),
    }

print(f"\n{'Model':<22}{'Accuracy':>10}{'Precision':>10}{'Recall':>8}{'F1':>8}{'CV Acc':>14}")
print("-"*72)
for n, r in results.items():
    print(f"{n:<22}{r['acc']:>10.4f}{r['prec']:>10.4f}"
          f"{r['rec']:>8.4f}{r['f1']:>8.4f}"
          f"{r['cv_mean']:>8.4f}±{r['cv_std']:.4f}")

best = max(results, key=lambda k: results[k]['f1'])
print(f"\n{best}")
print(classification_report(y_test, results[best]['pred'], target_names=CLASSES))

# ------------------------------------------------------------------
# STEP 5 — FIG 1: CONFUSION MATRICES
# ------------------------------------------------------------------

fig, axes = plt.subplots(1, 3, figsize=(15, 4))
for ax, (name, r), cmap in zip(axes, results.items(), ['Blues','Greens','Oranges']):
    cm = confusion_matrix(y_test, r['pred'])
    sns.heatmap(cm, annot=True, fmt='d', cmap=cmap, ax=ax,
                xticklabels=CLASSES, yticklabels=CLASSES,
                linewidths=0.5, annot_kws={'size':11})
    ax.set_title(f"{name}\nAcc: {r['acc']:.1%}", fontsize=11, fontweight='bold')
    ax.set_xlabel('Predicted', fontsize=9)
    ax.set_ylabel('Actual', fontsize=9)
    ax.tick_params(labelsize=8)
plt.suptitle('Fig. 1 — Confusion Matrices', fontsize=12, fontweight='bold', y=1.01)
plt.tight_layout()
plt.savefig('fig1_confusion_matrices.png', bbox_inches='tight')
plt.show()

# ------------------------------------------------------------------
# STEP 6 — FIG 2: MODEL COMPARISON
# ------------------------------------------------------------------

fig, ax = plt.subplots(figsize=(10, 5))
met_keys   = ['acc','prec','rec','f1']
met_labels = ['Accuracy','Precision','Recall','F1-Score']
x, w       = np.arange(len(met_keys)), 0.25
for i, (name, r) in enumerate(results.items()):
    vals = [r[m] for m in met_keys]
    bars = ax.bar(x + i*w, vals, w, label=name, color=COLORS[i], alpha=0.88, edgecolor='white')
    for bar, v in zip(bars, vals):
        ax.text(bar.get_x()+bar.get_width()/2,
                bar.get_height()+0.006, f'{v:.2f}',
                ha='center', va='bottom', fontsize=8, fontweight='bold')
ax.set_xticks(x+w)
ax.set_xticklabels(met_labels, fontsize=11)
ax.set_ylabel('Score', fontsize=11)
ax.set_ylim(0, 1.12)
ax.set_title('Fig. 2 — Classifier Performance Comparison', fontsize=12, fontweight='bold')
ax.legend(fontsize=10)
ax.grid(axis='y', alpha=0.3, linestyle='--')
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)
plt.tight_layout()
plt.savefig('fig2_model_comparison.png', bbox_inches='tight')
plt.show()

# ------------------------------------------------------------------
# STEP 7 — FIG 3: FEATURE IMPORTANCE
# ------------------------------------------------------------------

rf_model    = results['Random Forest']['model']
importances = rf_model.feature_importances_
sorted_idx  = np.argsort(importances)
feat_labels = [f.replace('_',' ').title() for f in FEAT]
palette     = plt.cm.RdYlGn(np.linspace(0.15, 0.85, len(FEAT)))
fig, ax = plt.subplots(figsize=(10, 5))
bars = ax.barh(
    [feat_labels[i] for i in sorted_idx],
    importances[sorted_idx],
    color=[palette[i] for i in range(len(sorted_idx))],
    edgecolor='gray', linewidth=0.5, alpha=0.9
)
for bar, val in zip(bars, importances[sorted_idx]):
    ax.text(bar.get_width()+0.002, bar.get_y()+bar.get_height()/2,
            f'{val:.3f}', va='center', fontsize=9, fontweight='bold')
ax.set_xlabel('Importance Score (Gini)', fontsize=11)
ax.set_title('Fig. 3 — Feature Importance (Random Forest)', fontsize=12, fontweight='bold')
ax.grid(axis='x', alpha=0.3, linestyle='--')
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)
plt.tight_layout()
plt.savefig('fig3_feature_importance.png', bbox_inches='tight')
plt.show()

# ------------------------------------------------------------------
# STEP 8 — FIG 4: ROC CURVES
# ------------------------------------------------------------------

y_bin = label_binarize(y_test, classes=[0,1,2])
fig, axes = plt.subplots(1, 3, figsize=(15, 4), sharey=True)
for ax, cls, cls_name in zip(axes, range(3), CLASSES):
    for (name, r), color in zip(results.items(), COLORS):
        prob      = r['model'].predict_proba(X_test_sc)[:, cls]
        fpr,tpr,_ = roc_curve(y_bin[:, cls], prob)
        ax.plot(fpr, tpr, label=f"{name} (AUC={auc(fpr,tpr):.2f})",
                color=color, linewidth=2)
    ax.plot([0,1],[0,1],'k--', linewidth=1, alpha=0.4)
    ax.set_title(cls_name, fontsize=11, fontweight='bold')
    ax.set_xlabel('False Positive Rate', fontsize=9)
    ax.set_ylabel('True Positive Rate', fontsize=9)
    ax.legend(fontsize=8, loc='lower right')
    ax.grid(alpha=0.25, linestyle='--')
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)
plt.suptitle('Fig. 4 — ROC-AUC Curves (One-vs-Rest)', fontsize=12, fontweight='bold')
plt.tight_layout()
plt.savefig('fig4_roc_curves.png', bbox_inches='tight')
plt.show()

# ------------------------------------------------------------------
# STEP 9 — FIG 5: DATASET OVERVIEW
# ------------------------------------------------------------------

fig, axes = plt.subplots(1, 2, figsize=(12, 4))
axes[0].pie(
    [len(df)],
    labels=[f'Student Stress Dataset\n(Kaggle, n={len(df)})'],
    autopct='%1.1f%%', colors=['#4472C4'],
    wedgeprops={'edgecolor':'white','linewidth':2},
    textprops={'fontsize':11}, startangle=90
)
axes[0].set_title('Data Source', fontweight='bold', fontsize=11)

counts = y.value_counts().sort_index()
b = axes[1].bar(CLASSES, counts.values,
                color=['#70AD47','#FFC000','#FF6B35'],
                edgecolor='white', alpha=0.9)
for bar, v in zip(b, counts.values):
    axes[1].text(bar.get_x()+bar.get_width()/2,
                 v+1, str(v), ha='center', fontweight='bold', fontsize=11)
axes[1].set_ylabel('Count', fontsize=10)
axes[1].set_title(f'Class Distribution (n={len(df)})', fontweight='bold', fontsize=11)
axes[1].grid(axis='y', alpha=0.3, linestyle='--')
axes[1].spines['top'].set_visible(False)
axes[1].spines['right'].set_visible(False)
plt.suptitle('Fig. 5 — Dataset Overview', fontsize=12, fontweight='bold')
plt.tight_layout()
plt.savefig('fig5_dataset_overview.png', bbox_inches='tight')
plt.show()

# ------------------------------------------------------------------
# STEP 10 — FIG 6: CROSS-VALIDATION
# ------------------------------------------------------------------

fig, ax = plt.subplots(figsize=(8, 4))
means = [results[m]['cv_mean'] for m in models]
stds  = [results[m]['cv_std']  for m in models]
bars  = ax.bar(list(models.keys()), means, yerr=stds, capsize=6,
               color=COLORS, alpha=0.88, edgecolor='white',
               error_kw={'elinewidth':1.5,'ecolor':'gray'})
for bar, m, s in zip(bars, means, stds):
    ax.text(bar.get_x()+bar.get_width()/2,
            bar.get_height()+s+0.01,
            f'{m:.3f}±{s:.3f}',
            ha='center', fontsize=9, fontweight='bold')
ax.set_ylabel('CV Accuracy', fontsize=11)
ax.set_ylim(0, 1.12)
ax.set_title('Fig. 6 — 5-Fold Cross-Validation', fontsize=12, fontweight='bold')
ax.grid(axis='y', alpha=0.3, linestyle='--')
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)
plt.tight_layout()
plt.savefig('fig6_cross_validation.png', bbox_inches='tight')
plt.show()

# ------------------------------------------------------------------
# STEP 11 — FIG 7: FEATURE DISTRIBUTIONS
# ------------------------------------------------------------------

fig, axes = plt.subplots(2, 3, figsize=(15, 8))
axes = axes.flatten()
eda_map = {
    'stress_level':      'Stress Level',
    'sleep_deprivation': 'Sleep Deprivation',
    'emotional_exhaust': 'Emotional Exhaustion',
    'study_hours':       'Study / Work Hours',
    'unmotivated':       'Loss of Motivation',
    'exercise_week':     'Exercise Frequency',
}
rc = ['#70AD47','#FFC000','#FF6B35']
rl = ['Low Risk','Moderate Risk','High Risk']
for ax, (col, title) in zip(axes, eda_map.items()):
    for lbl, color, rlabel in zip([0,1,2], rc, rl):
        ax.hist(df[df['label']==lbl][col],
                bins=5, alpha=0.65, color=color,
                label=rlabel, edgecolor='white', linewidth=0.5)
    ax.set_title(title, fontweight='bold', fontsize=10)
    ax.set_xlabel('Encoded Value', fontsize=9)
    ax.set_ylabel('Count', fontsize=9)
    ax.legend(fontsize=8)
    ax.grid(alpha=0.25, linestyle='--')
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)
plt.suptitle('Fig. 7 — Feature Distributions by Risk Class',
             fontsize=12, fontweight='bold')
plt.tight_layout()
plt.savefig('fig7_feature_distributions.png', bbox_inches='tight')
plt.show()

# ------------------------------------------------------------------
# STEP 12 — ZIP AND DOWNLOAD
# ------------------------------------------------------------------

charts = ['fig1_confusion_matrices.png','fig2_model_comparison.png',
          'fig3_feature_importance.png','fig4_roc_curves.png',
          'fig5_dataset_overview.png','fig6_cross_validation.png',
          'fig7_feature_distributions.png']

with zipfile.ZipFile('burnout_charts.zip','w') as zf:
    for f in charts:
        if os.path.exists(f):
            zf.write(f)

from google.colab import files
files.download('burnout_charts.zip')

print("\n" + "="*55)
print(f"  Dataset  : {len(df)} samples (Kaggle public dataset)")
print(f"  Training : {len(X_train)} | Testing : {len(X_test)}")
print()
for name, r in results.items():
    print(f"  {name}")
    print(f"    Accuracy  : {r['acc']*100:.1f}%")
    print(f"    Precision : {r['prec']*100:.1f}%")
    print(f"    Recall    : {r['rec']*100:.1f}%")
    print(f"    F1-Score  : {r['f1']*100:.1f}%")
    print(f"    CV Acc    : {r['cv_mean']*100:.1f}% ± {r['cv_std']*100:.1f}%")
    print()
print("="*55)